== Debes Nacer de Nuevo

Sermón predicado por William Dewsbury en Gracechurch Street,

el 16 del mes Tres de 1688

Mis Amigos,

A menos que sean regenerados y nazcan de nuevo, no pueden heredar el reino de Dios.

Esta es la palabra del Señor Dios para todos los hombres hoy.
Esto no se encuentra en una profesión superficial, en vana imaginación,
o en cualquier otra cosa con la que puedan engalanarse; no,
cada hombre y mujer en particular debe nacer de nuevo, o de lo contrario,
no podrá entrar en el reino de los cielos.
Esta era la doctrina de Cristo cuando estaba en el '`cuerpo preparado,`'^
footnote:[Hebreos 10:5]
en el que apareció en el mundo y le predicó a Nicodemo esta inmutable doctrina,
y es la doctrina que continúa hasta este momento,
y continuará mientras un hombre respire sobre la tierra.
No hay otro camino, ninguna otra puerta para entrar en la vida,
sino por esta gran obra de regeneración.

Ahora bien, para llegar a esta gran obra,
avanzar y viajar de la tierra al cielo (habiendo sido expulsados todos
del Paraíso por los querubines colocados junto con una espada encendida),
deben saber que no hay regreso a esa bendita vida,
sino mediante la pérdida de la vida que aflige al Espíritu de Dios,
y que hizo que el hombre fuera expulsado.
No hay otra manera de volver sino por medio del nuevo nacimiento.
Así como todos han sido expulsados y forzados a salir del Paraíso,
y los querubines y la espada encendida están colocados
para guardar el camino al árbol de la vida,
así deben regresar al favor de Dios, por medio de la luz de Cristo, y "`línea tras línea,
precepto tras precepto, un poquito aquí, un poquito allá`"^
footnote:[Isaías 28:10, 13]
dirigir sus mentes a la luz de Jesucristo.
Y así como '`el primer Adán fue hecho un alma viviente;
así el postrer Adán es un espíritu vivificante.`' Sepan esto con certeza,
que ningún hombre o mujer puede ser vivificado y levantado en la vida del postrer Adán,
hasta que la vida del primer Adán le sea quitada.

Así, pues,
cada uno trate sinceramente con su propio corazón. ¿Han llegado
ustedes a ser un pueblo muerto a la vida del primer Adán,
en cuya vida está obrando el misterio de iniquidad en cada parte del hombre?
Unos claman: "`Mirad, aquí está el Cristo`"; otros: "`Mirad, allí está`";
y cada uno sigue su propia imaginación acerca de la letra de la Escritura.
Pero esto no es más que el espíritu vano del hombre
que corre y se esfuerza por rescatarse a sí mismo;
y esta es la causa de que haya tanta profesión de Dios,
y tan poco de Su naturaleza manifestándose entre los hijos y las hijas de los hombres.
Pero todos ustedes que buscan ser regenerados, deben ir a la luz de Cristo;
no hay otro camino para ello.
Él escudriñará sus corazones, tratará sus mentes,
pondrá sus pecados en orden delante de ustedes y
descubrirá las iniquidades que los rodean.
Deben ver que son un pueblo perdido, un pueblo pecador,
y así sentir el peso de sus pecados sobre sus consciencias.
No hay otra manera de llegar a la vida.
Nunca se quejarán del pecado hasta que sean agobiados por él,
hasta que una trompeta suene en sus oídos y los despierte,
para que se levanten de entre los muertos y Cristo les dé luz.

No hay otro camino, querido pueblo,
deben llevar sus obras a la luz de Cristo y permanecer
en la sentencia de condenación. Si salvan sus vidas,
las perderán; y si pierden sus vidas por causa de Cristo,
su vida eterna no corre peligro.
Juan el Bautista, el precursor de Cristo, declaró: "`Yo a la verdad os bautizo en agua;
pero viene uno más poderoso que yo,
de quien no soy digno de desatar la correa de su calzado;
él os bautizará en Espíritu Santo y fuego.
Su aventador está en su mano, y limpiará su era, y recogerá el trigo en su granero,
y quemará la paja en fuego que nunca se apagará.`" ¿De qué les
sirve leer las Escrituras si no conocen este bautismo de fuego,
el que todos los regenerados deben experimentar?
No se engañen,
Cristo aparecerá en llama de fuego y tomará venganza
de todos aquellos que no conocen a Dios,
y que no obedecen el evangelio de nuestro Señor Jesucristo.

Hoy estoy aquí como testigo del Señor de vida,
no hay forma de que las personas lleguen a la salvación,
sino conociendo a Cristo revelado en sus corazones.
¿Qué está haciendo Él allí sino tomando venganza de la mente carnal,
de toda la autocomplacencia y de los afectos desordenados?
Él viene con venganza para quitarles la vida;
Él los bautizará con el Espíritu Santo y con fuego.
Si no conocen este bautismo, no son verdaderos Cristianos.
Nunca mirarán a la muerte a la cara con gozo, ni descenderán a la tumba con triunfo.
Si viven como en casa en el cuerpo, huyen por sus vidas,
y no están dispuestos a perderla por Cristo si son llamados a ello;
y si no quieren que Cristo los lave (algunos rechazarán
esto por timidez y otros por amor al yo) yo les digo,
que si Cristo no los lava,
no tiene parte con Él. Deben ir a Cristo para que los purifique en el horno de fuego.
El día del Señor arderá como un horno (como lo dice el profeta); este es un día terrible,
un día de venganza, el día del Señor Jesucristo que redime a Su pueblo de sus pecados.
Sion es redimida con juicio y establecida con justicia.
No hagan el camino al cielo más fácil en sus mentes
e imaginaciones de lo que en realidad es,
ni crean que es suficiente vivir en un cumplimiento externo de los caminos de Dios.
Si sus voluntades permanecen vivas y sus corrupciones siguen sin ser crucificadas,
el juicio de Dios será la porción de ustedes.

Por tanto, en el nombre del Señor vengan conmigo.
He venido a declarar lo que he oído y visto del Padre.
Vengan y examinen sus consciencias.
¿Han llevado sus obras a la luz?
Si lo han hecho, entonces han recibido condenación sobre sí mismos,
y la altivez de ustedes ha sido abatida y humillada, y se ven a sí mismos pobres,
miserables y desventurados delante del Dios eterno.
Independientemente de lo que sepan de la mente de Dios, ¿han reformado sus caminos?
Vengan conmigo y díganme, ¿cuál es el fundamento de la fe y de la confianza de ustedes?
Lean el libro de la consciencia; ¿no tienen fundamento para su fe?
Se han revestido de la fe reformada, pero ¿han vivido una vida no reformada?

Examínate y pruébate, hombre o mujer.
¿Velas sobre ti mismo y te mantienes en un sentido de tu próxima destrucción,
pese a todas tus credenciales y reforma parcial?
¿Te esfuerzas por entrar por la puerta estrecha y el camino angosto,
para perder la vida de tu voluntad,
la vida del primer Adán? La justicia de Dios no te permitirá
hacer de tus deberes y credenciales un salvador;
o de tomar las joyas de Dios y adornarte con ellas.
No, tú no puedes ser salvo sin la justicia de Dios en Cristo Jesús. ¿Qué dice tu consciencia?
¿Estás siendo llevado a un cambio de tu mente y de tu conducta?
¿Estás dispuesto a separarte de tus pecados, junto con tu orgullo y altivez?
¿Estás dispuesto a separarte de tus viles afectos?
Esta es la obra de la gracia de Dios sobre ti.
¿Colocas tu confianza en tus deberes y cualidades,
y tomas las joyas y ornamentos de Dios y te engalanas con ellos?
"`Tomaste mis joyas,`" dice el Señor, "`y te echaste como ramera`";
si te vuelves al Señor y te humillas, y atraviesas esta tribulación,
serás feliz para siempre.
Este juicio de Dios, esta espada encendida que se revuelve por todos lados,
te guardará de volverte al pecado.
Te llevará a Cristo y te separará de toda esperanza
de salvación que no sea a través de Él,
y te hará ver la absoluta necesidad de un Salvador,
y que tu vida está escondida con Cristo en Dios.

La infinita bondad de Dios para con los hombres consiste en "`apartar del varón la soberbia,`"^
footnote:[Job 33:17]
y humillarlos bajo Su poderosa mano.
Esta es la condición de las pobres criaturas a las que el
Altísimo les ha dado muerte por medio de Sus manos.
¿Cómo puedo saber si he sido matado y bautizado, y si he llegado a la sinceridad?
Los que tienen este bautismo entran a la vida celestial.
Si amas la luz de Jesucristo, así será contigo, Dios hará una obra rápida en tu tierra.
Pondrá tus pecados en orden delante de ti y te hará velar en oración,
te conducirá en santidad de vida y conducta,
y hará que te aborrezcas y que desprecies toda la pompa,
los placeres y vanidades de este mundo.
Cuando Él te haya adornado con Sus gracias, entonces mantente atento a la luz,
y en la luz de Cristo verás la luz, y sabrás que todo lo que has hecho y puedas hacer,
no es más que tu deber.
Y si esperas diligentemente verás más luz,
y la espada que sale de la boca de Cristo (quien es llamado la Palabra de Dios)
cortará todas tus esperanzas de salvación en cualquier cosa que hayas hecho,
en cualquiera de tus cualidades, y en cualquier cosa que puedas hacer;
de modo que serás un alma sin esperanza,
sin nada en tu propio sentido y comprensión. El poder
del primer Adán debe morir delante de Él,
y tú debes gritar: "`¡Soy una criatura muerta, perdida y deshecha!
Hay una vida escondida con Cristo en Dios para mí,
pero no podré tenerla hasta que haya muerto, y caiga en la voluntad de Dios,
me convierta en un niño pequeño,
y sea despojado de toda la excelencia que he alcanzado para mí. Debo llegar
a un sentido de mi propia miseria y postrarme a los pies de Dios.
Y cuando me haya convertido en un niño pequeño,
haya sido humillado y haya muerto a mi propia voluntad,
y a toda confianza en mi propia justicia, ciertamente viviré una vida santa.
Pero daré toda la vida que una vez tuve,
por esa vida que está escondida con Cristo en Dios.`"

¡Oh, cualquiera que llegue tan lejos no se perderá la vida eterna!
Todas las personas deshonestas que desean tener salvación por medio de Cristo,
pero que no lo dejan ejercer Su poder celestial, Su glorioso poder principesco,
para que los bautice en Su muerte,
ciertamente quedarán cortas de la salvación. Pero todas las que
se entregan a Cristo para ser redimidas a través del juicio,
y han llegado a ser como niños pequeños, estas están en un estado feliz.
Ustedes saben que nuestro Señor Jesucristo tomó a un niño pequeño en sus brazos y dijo:
"`De cierto os digo, que si no os volvéis y os hacéis como niños,
no entraréis en el reino de los cielos.`"
Todos deben llegar a ser como un niño pequeño,
y depender de la misericordia y gracia gratuita de Dios.
Todos deben llegar a una santa rendición de sus voluntades a la disposición de Dios.
Si van a Cristo como niños pequeños y dependen de Él,
no van a quedar cortos de Su salvación. Ésta es concedida
a las almas que oyen la voz de Cristo,
porque los que oyen la voz del Hijo de Dios vivirán.

Estoy aquí como testigo del Dios del cielo, yo nunca oí la voz de Cristo,
como seguidor Suyo, hasta que morí y fui bautizado,
y yací como un niño pequeño bajo Sus castigos celestiales.
Pero tan pronto como mi alma fue llevada a ese estado, en mi humillación, ¡oh, entonces!,
el terrible juicio fue quitado, el libro de la vida abierto para mí,
y el Señor me habló consoladoramente: "`Yo te he amado con amor eterno.`"
Por tanto, fui hecho Cristiano a través del día de venganza, ardiente como un horno,
y la altivez y el orgullo del hombre en mí fueron abatidos.
Ahora bien,
es a través de esta sumisión a la muerte de Cristo
que las personas pueden morir para vida;
y bienaventurados los muertos que mueren en el Señor,
porque ellos descansarán de sus trabajos y sus obras con ellos siguen.

¡Acaben entonces con sus propias voluntades, con su orgullo y altivez,
hipocresía y engaño, y con toda dependencia en cualquier cualidad propia!
Deben llegar a tener sus vidas separadas de ustedes, o de lo contrario,
perecerán. Aquellos que mueran con Cristo y estén dispuestos a morir por Él,
a éstos Él es revelado como Salvador.
Él vino a nosotros en los días de Su carne y cumplió con la voluntad de Su Padre.
Fue clavado en la cruz.
Cuando el Hijo de Dios llegó a la profundidad de Sus sufrimientos, clamó: "`Dios Mío,
Dios Mío, ¿por qué Me has abandonado?`"
Esto fue por tu causa y por la mía,
y por la de todo hombre y mujer que cree en Él. Él
bebió la copa que Su Padre le había dado a beber.
Si así se hizo con el árbol verde, ¿qué se hará con el seco?
Él fue delante de nosotros,
para que cuando venga de nuevo nos tome para Sí y nos saque de la inmundicia del pecado,
y podamos ser hechos nuevas criaturas.

Ahora, si no nacemos de nuevo, no podemos entrar en el reino de Dios;
y no nos convertimos en nuevas criaturas, hasta que hayamos muerto al viejo hombre.
Tú debes morir a tu orgullo y altivez, a la corrupción de tu propia voluntad,
y a todo egoísmo; Dios debe quemar estas cosas en ti.
El Espíritu Santo no destruirá ni quemará nada en ti,
sino aquello que traiga fuego eterno sobre tu alma.
'`Hazme saber, oh tú, a quien ama mi alma, ¿dónde está el camino de vida?
¿Por qué había de estar yo como errante junto a los rebaños de tus compañeros?`' Ahora,
todo el que viva en el cuerpo en el seno del yo, tome esto para sí:
Aunque profeses la verdad y vivas en conformación externa con ella,
si secretamente complaces tu voluntad corrupta, y vives una vida agradable a la carne,
y consultas con sangre y carne, y no te desprendes de tus concupiscencias,
no puedes disfrutar al Señor de vida.
"`Mientras estoy en el cuerpo,
estoy ausente del Señor.`" El cuerpo de pecado es como un imán
que te saca de la vida de Dios y de gloriarte en la cruz de Cristo.
Es carne y sangre, y la carne y sangre no pueden heredar el reino de Dios.
Por amor al Señor, por amor a tu alma y por amor a tu felicidad eterna,
no pospongas esta obra, sino búscala, y será perfeccionada.
Experimenta a Cristo siendo revelado en ti por Su Espíritu Santo y fuego.
Dios te redimirá por medio del espíritu de juicio y fuego,
no por deambular afuera en tu mente; sino que debes conocer a
'`Cristo _en ti,_ a menos que estés reprobado.`'^
footnote:[2 Corintios 13:5]

Si Él ha colocado tus ojos y corazón en Él, y ha hecho que mojes tu lecho con lágrimas;
si Él ha interrumpido tu sueño de modo que has gritado:
"`¡Seré condenado y nunca llegaré a la salvación!`" (ese será tu lloro;
una vez fue el mío), oh, entonces, no dejes que tus ojos se adormezcan,
ni que tus párpados descansen hasta que estés seguro de que el Señor es tu Dios.
Si encuentras estas señales, entonces estás en tu camino; de lo contrario,
serás como un arco engañoso y nunca permanecerás en el juicio.
Si rechazas el consejo de Dios contra ti,
te rehúsas a ser crucificado con Cristo y a ser bautizado con Su bautismo,
nunca tendrás vida.
Pero por Su bautismo y a través de la operación celestial
de Su Espíritu (teniendo fe en el nombre de Cristo),
serás unido a Él en justicia eterna.
Se nos traerá la salvación y se nos otorgará la vida eterna,
esa vida que está escondida con Cristo en Dios.
Él le dará esto a cada pobre y afligida alma que se someta a Su bendita voluntad,
y crea en el Señor Jesucristo.
Esta no es una fe de nuestra propia hechura, ni un vestido de nuestro propio bordado,
sino la que el Señor nos ha dado.

¡Oh, feliz el hombre o la mujer que obtiene este don de Dios!
Oh, ¿quién no perderá su vida por esta vida eterna?
¿Quién no morirá por esta vida eterna?
El asunto radica en la muerte de sus voluntades.
Y cuando hayan hecho la voluntad de Dios,
entonces vigilen que sus voluntades permanezcan muertas,
y que ese maldito _yo_ no tome las joyas de Dios, o Sus brazaletes y adornos,
para otorgárselos a sí mismo, pintar y engalanar al maldito yo,
o tomar los miembros de Cristo y hacerlos miembros de una ramera.
Si están muertos a sus propias voluntades,
han resucitado con Cristo y recibirán la resurrección para vida eterna.
¡Oh, crucifiquen el yo, desechen el mundo, pisotéenlo y pisoteen todas sus cosas,
y considérenlas escoria y estiércol en comparación con Cristo,
a quien el Padre ha revelado ser nuestra vida en los días de dolor y luto,
en el día de nuestra calamidad,
en el día que gritamos que nuestra esperanza se ha perdido!

Así ha sido con las personas más santas en la tierra.
No es por sus propias obras de justicia que pueden ser salvas;
Cristo viene a cortar todo eso,
para que sean injertadas en Él y justificadas por Su gracia.
No hagan de esto un asunto de conversación, diciendo: "`Yo ya he oído esto y aquello`";
sino miren en sus propios corazones y vean qué obras celestiales
hay allí. ¿Qué han experimentado ahí del poder del Señor Jesucristo?
¿Les ha hecho Su poder aborrecer a este mundo, y al amor desmedido por la creación,
para que disfruten todas estas cosas como si no las disfrutaran?
Cuando morimos y somos crucificados a este mundo, no podemos evitar decir:
"`Mi vida está en Cristo.`"
Llegamos a no atribuirnos nada a nosotros mismos, y todo a Cristo.

He aquí una bendita armonía: Corazones quebrantados, espíritus derretidos, y sin embargo,
almas gozosas.
Pobres criaturas que lloraban,
suspiraban y clamaban delante del Señor en lugares secretos diciendo:
"`Cortada es mi esperanza, me recostaré en Tu voluntad, oh, Dios;
has lo que desees conmigo.
Es Tu soberana complacencia o don gratuito, si me das la vida o me la niegas.`"
¡Oh, debemos rendirnos a la voluntad de Dios!
Así fue con el Señor Jesús, y así debe ser con cada verdadero santo de Dios.
Ustedes deben ser humillados como niños pequeños antes de que el juicio sea quitado,
y la amorosa bondad de Dios sea sellada en sus almas; pero si buscan esta obra de Dios,
la encontrarán; si la buscan sobre sus camas, en todas sus labores e intereses,
en todos sus puestos y relaciones.
Si insisten en pos del nuevo nacimiento,
deben disfrutar este mundo como si no lo disfrutaran,
y tener una esposa como si no la tuvieran, porque la forma de este mundo está pasando.

Pero déjenme decirles,
un mundo nuevo viene por la regeneración. El nuevo
hombre no se enaltece en su propia mente,
sino que permanece bajo ante sus propios ojos;
espera que la sabiduría de Dios lo gobierne, y es como un mayordomo de la gracia de Dios,
para darles a los que están en necesidad.
Cuando un hombre es regenerado y nace de nuevo, se contenta tanto con pan y agua,
como con todos los placeres de este mundo.
¿Cuál es la razón? Su propia voluntad se ha ido y ha sido puesta bajo sus pies,
junto con todo lo que le da vida a todos sus deseos y afectos vanos.
Oh, todo en el interior está en armonía. Hay un hombre
alabando a Dios y bendiciendo Su santo nombre,
sin enredos que aparten el corazón de servir a Dios y de buscar Su gloria.
Y si Dios llamara al esposo de la esposa,
o a la esposa del esposo para la gloria de Su nombre, no hay lloros, ni quejas,
ni clamores, sino más bien, una renuncia a ellos,
y una alabanza y bendición a Dios cuando son llamados a tal ejercicio.
Y si no son llamados así,
entonces fijan sus corazones para glorificar a Dios en sus varios lugares y posiciones,
y tienen pleno contentamiento en bendita rendición. Aquí son sacrificadas sus voluntades,
y alaban a Dios porque no tienen más deseo que "`Señor,
hágase tu voluntad,`" alabándolo siempre a Él,
y teniendo el temor y la gloria de Dios delante de sus ojos.
Toda maldad es planeada para complacer las voluntades de los hombres; es decir,
en el consejo del corazón que Dios no gobierna.
¿Vivirán como Cuáqueros?
Entonces deben vivir de una manera que será menospreciada,
y cada uno debe caminar en humildad y amor,
y en verdadero conocimiento del Dios del cielo.
He aquí entonces un nuevo mundo, y las modas del viejo mundo han desaparecido.
Todo orgullo, altivez, enojo y pisoteo de unos contra otros ha desaparecido,
todo ha muerto por la operación de Cristo.

¿Qué queda entonces?
Cristo en mí, y todos somos uno en Él. Cristo dio Su vida por ustedes y por mí,
y ahora reina en mí. Él ha preparado mi cuerpo para morir por la verdad,
como Su '`cuerpo preparado`' fue entregado por mi pecado.
Es una necedad cuando los hombres hacen profesión de Cristo, y sin embargo,
viven en codicia, profanación, sensualidad y cosas similares.
Los que han llegado a este nacimiento celestial, buscan las cosas de arriba,
y no pueden hacer otra cosa.
Primero hagan el árbol bueno y el fruto será bueno.
Ustedes deben ser injertados en la vid de la justicia de Dios.
¡No desprecien el día de su visitación! ¿De qué me
servía a mí leer que otro había nacido de nuevo,
hasta que yo mismo fui muerto y experimenté el bautismo celestial de Jesucristo,
y vi la espada encendida lista para matarme en cada vuelta?
La luz de Cristo me convenció de pecado y Su justicia me justificó,
entonces me fueron abominables todas las obras que le impedían el paso a mi alma a Cristo.
Al ligar mi alma con Él, Cristo se apoderó de mí y obró eficazmente en mí;
y ahora hay testimonio de Cristo en mí de que Él ha sellado mi alma para el día
de mi redención. He aquí cierto viaje y cierto camino que nadie se puede perder,
siempre y cuando esté dispuesto a perder su vida por Cristo.
Si no están listos ni dispuestos a perder sus vidas por Cristo,
no pueden venir aquí. Nadie entra por la puerta estrecha ni el camino angosto,
sino el que muere en unidad celestial con Cristo.
¡Oh, amigos, vaciémonos de nosotros mismos,
para que Cristo nos pueda llenar! ¡No seamos nada ante nuestros propios ojos,
para que seamos todo en Él y recibamos Su plenitud!

Ahora los encomiendo al testigo de Dios,
para que recuerden lo que se ha dicho en su presencia.
Pero consideren, que si no le prestan atención,
ello los seguirá y será una plaga para ustedes por toda la eternidad.
Si no se rinden a Cristo en este día que arde como un horno,
entonces deberán morar en ese fuego cuando salgan del cuerpo,
y no habrá forma de apagar el fuego que arderá para siempre.
Pero si son tan sabios como para rendirse a Cristo, e ir a Él como niños pequeños,
verán que eso no estorba sus responsabilidades terrenales.
Aunque el mundo los considere tontos,
aun así tendrán la sabiduría celestial para hacer lo que hacen para Dios.
Se comportarán con sus esposas como ante los ojos de Dios,
para que ellas sean santificadas para ustedes, y ustedes para ellas.
Se comportarán como es debido con sus hijos y con sus siervos,
y así abundarán en gracia y en toda buena obra,
lo cual redundará en beneficio eterno para ustedes.

¡Oh, les ruego, por amor del Señor,
esperen la luz de Cristo para que los guíe! Aprendan de Él a ser mansos y humildes,
entonces serán felices.
Porque Él mora con los humildes, pero al altivo mira de lejos.
Este nuevo nacimiento, que es una obra verdadera, y una obra real y celestial,
los hará así para siempre.
¡Oh, hagan lugar para Cristo en sus corazones, o de lo contrario,
es probable que Él no habite con ustedes nunca;
porque Él ama habitar con el pobre y humilde y contrito
de Espíritu! Él aborrece al soberbio,
pero vaciará sus almas para poder llenarlas.

Por tanto, los encomiendo a Dios.
He estado retenido por mucho tiempo bajo una gran debilidad,
y estuve inquieto hasta que pude venir a esta gran ciudad
de Londres para predicar el evangelio eterno entre ustedes;
y ahora ven que estoy aquí entre ustedes.
Vamos, vuélvase cada uno a su interior.
No dejen que estas palabras, que pasan a través de un vaso despreciable,
sean un discurso desnudo y vacío de la verdad para ustedes,
que sólo oyen y luego no tienen más cuidado de su salvación.
Cuídense de despreciar la luz que brilla en medio de ustedes,
sino sigan adelante en la obra celestial que está establecida en el poder de Jesucristo;
es decir, a través del juicio para muerte, entonces Él les dará vida eterna.
Que el Señor confirme esto y descanse sobre sus corazones,
para que estén muertos a las cosas del mundo.
No nos hemos acercado al Monte Sinaí, que da a luz servidumbre,
sino que nos hemos acercado al monte de Sion, a la ciudad del Dios vivo,
Jerusalén la celestial, a la compañía de muchos millares de ángeles,
a la congregación e iglesia de los primogénitos que están inscritos en los cielos,
a Dios el Juez de todos, a los espíritus de los justos hechos perfectos,
a Jesús el Mediador del nuevo pacto,
y a la sangre rociada que habla mejor que la de Abel.
Esta es la herencia de los redimidos del Altísimo.
¡Bendito sea el nombre del Señor! ¡Oh, descansemos en esperanza,
hasta que Él nos lleve a humildad y a una mente baja,
para que nos pueda revestir con gloria celestial según Su promesa:
"`Yo embelleceré Mi casa con gloria,
dice el Señor.`" Esta es la porción del pueblo pobre, que se postra delante del Señor,
para que Él los levante y sea todo en todo para ellos.
Y en Su bendita presencia tengan gozo y ríos de delicias a Su diestra para siempre.
